/**
 * @file main.c
 * @brief STM32 USB CDC example using Plotter library
 *
 * Uses USB CDC (Virtual COM Port) to stream sensor data to PlotterApp.
 * Generated with STM32CubeMX with USB Device and CDC class enabled.
 *
 * @version 2.0
 * @date 2025-12-10
 */

#include "main.h"
#include "usb_device.h"
#include "usbd_cdc_if.h"
#include "../../common/plotter.h"
#include <math.h>

#define SAMPLE_RATE_MS 20  // 50 Hz
#define PLOTTER_EXAMPLE_USE_WAVEFORMS 1  // 1 = sine + sawtooth, 0 = original example
#define WAVE_PERIOD_MS 2000UL
#define WAVE_MIN 0.0f
#define WAVE_MAX 3.3f

#if !PLOTTER_EXAMPLE_USE_WAVEFORMS
ADC_HandleTypeDef hadc1;
#endif
TIM_HandleTypeDef htim2;

Plotter plotter;
uint32_t lastSample = 0;

// Send function for USB CDC
void usbSend(const char* data, uint16_t length) {
    CDC_Transmit_FS((uint8_t*)data, length);
}

void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_TIM2_Init(void);
#if !PLOTTER_EXAMPLE_USE_WAVEFORMS
static void MX_ADC1_Init(void);
#endif

int main(void) {
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_USB_DEVICE_Init();
#if !PLOTTER_EXAMPLE_USE_WAVEFORMS
    MX_ADC1_Init();
#endif
    MX_TIM2_Init();

    // Initialize plotter with timestamp
    plotter_init(&plotter, usbSend, 1);
    plotter_set_start_time(&plotter, HAL_GetTick());

    HAL_TIM_Base_Start(&htim2);

    while (1) {
        uint32_t currentTime = HAL_GetTick();

        if (currentTime - lastSample >= SAMPLE_RATE_MS) {
            lastSample = currentTime;

#if PLOTTER_EXAMPLE_USE_WAVEFORMS
            float range = WAVE_MAX - WAVE_MIN;
            float phase = (float)(currentTime % WAVE_PERIOD_MS) / (float)WAVE_PERIOD_MS;
            float angle = phase * 6.283185307f;
            float offset = WAVE_MIN + range * 0.5f;
            float amplitude = range * 0.5f;
            float sineValue = offset + amplitude * sinf(angle);
            float sawValue = WAVE_MIN + range * phase;

            plotter_send(&plotter, 0, sineValue, currentTime);
            plotter_send(&plotter, 1, sawValue, currentTime);
#else
            // Read ADC
            HAL_ADC_Start(&hadc1);
            if (HAL_ADC_PollForConversion(&hadc1, 10) == HAL_OK) {
                uint32_t rawValue = HAL_ADC_GetValue(&hadc1);
                float voltage = (rawValue / 4095.0f) * 3.3f;

                // Send data point (channel 0)
                plotter_send(&plotter, 0, voltage, currentTime);
            }
            HAL_ADC_Stop(&hadc1);
#endif
        }

        // Small delay to prevent blocking
        HAL_Delay(1);
    }
}

void SystemClock_Config(void) {
    // Configure system clock (generated by CubeMX)
    // This is a placeholder - use your actual clock configuration
}

#if !PLOTTER_EXAMPLE_USE_WAVEFORMS
static void MX_ADC1_Init(void) {
    // Configure ADC (generated by CubeMX)
    // This is a placeholder - use your actual ADC configuration
}
#endif

static void MX_TIM2_Init(void) {
    // Configure timer (generated by CubeMX)
    // This is a placeholder - use your actual timer configuration
}

static void MX_GPIO_Init(void) {
    // Configure GPIO (generated by CubeMX)
    // This is a placeholder - use your actual GPIO configuration
}

void Error_Handler(void) {
    __disable_irq();
    while (1) {
        // Error state
    }
}
